const ACTION_TYPES = {
    TOGGLE_NEVER_COOK: "TOGGLE_NEVER_COOK",
    TOGGLE_NEVER_ASSIST: "TOGGLE_NEVER_ASSIST",
    TOGGLE_NEVER_CLEAN: "TOGGLE_NEVER_CLEAN",
    TOGGLE_SHIFT: "TOGGLE_SHIFT",
};

export default ACTION_TYPES;
