const ACTION_TYPES = {
    TOGGLE_NEVER_COOK: "TOGGLE_NEVER_COOK",
    TOGGLE_NEVER_ASSIST: "TOGGLE_NEVER_ASSIST",
    TOGGLE_NEVER_CLEAN: "TOGGLE_NEVER_CLEAN",
    TOGGLE_SHIFT: "TOGGLE_SHIFT",
    TOGGLE_CHECKED_STATE: "TOGGLE_CHECKED_STATE",
    SET_INPUT_VALUE: "SET_INPUT_VALUE",
    CLEAR: "CLEAR",
};

export default ACTION_TYPES;
